import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}
  
        </AuthProvider>
        <Toaster
          position="top-center"
          toastOptions={{
            classNames: {
              toast: "bg-gray-900 text-white border border-gray-700",
              success: "bg-green-600 text-white",
              error: "bg-red-600 text-white",
              warning: "bg-yellow-500 text-black",
            },
          }}
        /> 
      </body>
    </html>
  );
}
